#
# This file is part of the RPSGuestbookBundle package.
#
# (c) Yos Okus <yos.okus@gmail.com>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.

RPS\GuestbookBundle\Model\Entry:
    properties:
        name:
            - NotBlank:
                message: rps_guestbook.name.blank
            - Length:
                min: 3
                max: 100
                #max: 255
                minMessage: rps_guestbook.name.short
                maxMessage: rps_guestbook.name.long

        email:
            - NotBlank:
                message: rps_guestbook.email.blank
            - Email:
                message: rps_guestbook.email.invalid
            - Length:
                max: 100
                #max: 255
                minMessage: rps_guestbook.email.short
                maxMessage: rps_guestbook.email.long

        comment:
            - NotBlank:
                message: rps_guestbook.comment.blank
            - Length:
                min: 2
                #max: 255
                minMessage: rps_guestbook.comment.short
                maxMessage: rps_guestbook.comment.long
